### ISSUE TITLE
Messages are not being sent. Fishtext connector

### ISSUE THREAD

**Issue by GoogleCodeExporter** [satyajit319/websmsdroid#296]
```
What steps will reproduce the problem?

1. Open WebSMS
2. Select a contact and write the message
3. Click on send button


What is the expected output? What do you see instead?

I expect the message to be sent :P


What version of the product are you using? On what operating system?

HTC Desire. official Froyo
WebSMS 3.1.9
Fishtext connector 1.2.2

Please provide any additional information below.

The last message that I could send correctly was on 2010-08-01 10:01:21. I 
think I upgraded Websms from the market after that date. I realized that 
messages weren't being sent yesterday 2010-08-09.

Balance refreshes correctly, so the credentials are OK.

The notification message appears as if the message were being sent correctly, 
and disappears when it "is" sent.

I can send messages directly from the Fishtext webpage, so Fishtext is also OK.

Also, I'm getting these messages in the logcat, but I'm not sure if they are 
useful:

E/BroadcastReceiver(28311): BroadcastReceiver trying to return result during a 
non-ordered broadcast
E/BroadcastReceiver(28311): java.lang.RuntimeException: BroadcastReceiver 
trying to return result during a non-ordered broadcast
E/BroadcastReceiver(28311):     at 
android.content.BroadcastReceiver.checkSynchronousHint(BroadcastReceiver.java:45
1)
E/BroadcastReceiver(28311):     at 
android.content.BroadcastReceiver.setResultCode(BroadcastReceiver.java:237)
E/BroadcastReceiver(28311):     at 
de.ub0r.android.websms.connector.common.Connector.onReceive(Connector.java:226)
E/BroadcastReceiver(28311):     at 
android.app.ActivityThread.handleReceiver(ActivityThread.java:2941)
E/BroadcastReceiver(28311):     at 
android.app.ActivityThread.access$3200(ActivityThread.java:135)
E/BroadcastReceiver(28311):     at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2198)
E/BroadcastReceiver(28311):     at 
android.os.Handler.dispatchMessage(Handler.java:99)
E/BroadcastReceiver(28311):     at android.os.Looper.loop(Looper.java:144)
E/BroadcastReceiver(28311):     at 
android.app.ActivityThread.main(ActivityThread.java:4937)
E/BroadcastReceiver(28311):     at java.lang.reflect.Method.invokeNative(Native 
Method)
E/BroadcastReceiver(28311):     at java.lang.reflect.Method.invoke(Method.java:521)
E/BroadcastReceiver(28311):     at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/BroadcastReceiver(28311):     at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
E/BroadcastReceiver(28311):     at dalvik.system.NativeStart.main(Native Method)
W/AdMobSDK(27703): Ignoring requestFreshAd() because we are requesting an ad 
right now already.
D/WebSMS  (27703): SMS: -> bc: de.ub0r.android.websms.connector.INFO
E/BroadcastReceiver(27703): BroadcastReceiver trying to return result during a 
non-ordered broadcast
E/BroadcastReceiver(27703): java.lang.RuntimeException: BroadcastReceiver 
trying to return result during a non-ordered broadcast
E/BroadcastReceiver(27703):     at 
android.content.BroadcastReceiver.checkSynchronousHint(BroadcastReceiver.java:45
1)
E/BroadcastReceiver(27703):     at 
android.content.BroadcastReceiver.setResultCode(BroadcastReceiver.java:237)
E/BroadcastReceiver(27703):     at 
de.ub0r.android.websms.connector.sms.ConnectorSMS.onReceive(ConnectorSMS.java:11
9)
E/BroadcastReceiver(27703):     at 
android.app.ActivityThread.handleReceiver(ActivityThread.java:2941)
E/BroadcastReceiver(27703):     at 
android.app.ActivityThread.access$3200(ActivityThread.java:135)
E/BroadcastReceiver(27703):     at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2198)
E/BroadcastReceiver(27703):     at 
android.os.Handler.dispatchMessage(Handler.java:99)
E/BroadcastReceiver(27703):     at android.os.Looper.loop(Looper.java:144)
E/BroadcastReceiver(27703):     at 
android.app.ActivityThread.main(ActivityThread.java:4937)
E/BroadcastReceiver(27703):     at java.lang.reflect.Method.invokeNative(Native 
Method)
E/BroadcastReceiver(27703):     at java.lang.reflect.Method.invoke(Method.java:521)
E/BroadcastReceiver(27703):     at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/BroadcastReceiver(27703):     at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
E/BroadcastReceiver(27703):     at dalvik.system.NativeStart.main(Native Method)



```

Original issue reported on code.google.com by `jmsrun@gmail.com` on 10 Aug 2010 at 8:18

**Comment by GoogleCodeExporter** [comment]
```
Ok, I'm silly. My fault, sorry :-(.
I should change the issue for: "Enhancement: do not let the application try to 
send a message without a valid country code configured"
```

Original comment by `jmsrun@gmail.com` on 10 Aug 2010 at 9:59

**Comment by GoogleCodeExporter** [comment]
```
:p
```

Original comment by `felix.bechstein` on 12 Aug 2010 at 5:21
- Changed state: **Invalid**
