### ISSUE TITLE
SMSdroid crashes when SMS is opened by LauncherPro SMS Widget

### ISSUE THREAD

**Issue by GoogleCodeExporter** [satyajit319/websmsdroid#318]
```
LauncherPro contains an SMS Widget for the Homescreen. Whenever a SMS is opened 
by clicking on the SMS, SMSDroid starts and immediatly crashes.

I attached a LogCat incl. the Null Pointer Exception to this Issue. 

```

Original issue reported on code.google.com by `jos...@schallwellenreiter.org` on 27 Aug 2010 at 10:28

Attachments:
- [launcherpro-smsdroid_logcat.txt](https://storage.googleapis.com/google-code-attachments/websmsdroid/issue-318/comment-0/launcherpro-smsdroid_logcat.txt)

**Comment by GoogleCodeExporter** [comment]
```
Opening the SMS with the builtin SMS App or WebSMS works fine & without crash
```

Original comment by `jos...@schallwellenreiter.org` on 27 Aug 2010 at 10:31

**Comment by GoogleCodeExporter** [comment]
```
happens at least with Versions 0.2.1 and 0.2.2
```

Original comment by `jos...@schallwellenreiter.org` on 27 Aug 2010 at 10:55

**Comment by GoogleCodeExporter** [comment]
```
hm. it's trying to start the messagelist without telling it which thread should 
be loaded o.O
i'm not sure if this is a bug in launcher pro.

which screen is launched when choosing the stock sms reader? the main view or a 
single thread?
```

Original comment by `felix.bechstein` on 27 Aug 2010 at 3:26
- Changed state: **NeedMoreInfos**
- Added labels: **Component-Logic**, **Product-SMSdroid**

**Comment by GoogleCodeExporter** [comment]
```
Hi,
using the Stock-SMS App, the single thread with the SMS (and previous SMS by 
that Person)  gets loaded,
WebSMS loads fine but without pre-filled number/name.

Just tried it with ChompSMS and even there the SMS/Thread loads fine.
```

Original comment by `jos...@schallwellenreiter.org` on 27 Aug 2010 at 4:16

**Comment by GoogleCodeExporter** [comment]
```
ok, but its rather strange, as there is no URI is given by launcher pro :/
i'll investigate it with your help after vacation is over.
please be patient.
```

Original comment by `felix.bechstein` on 27 Aug 2010 at 5:08
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
No Problem,
found the solution ;)

LauncherPro starts the intent without a URI in the data field. Instead the 
thread_id is passed in the Extras-Field of the Intent. Keyname is "thread_id" 
and the value is of type long. 
I couldn't find a Documentation about valid mms-sms intents, but as the 
original google SMS App handles the extras field also, i guess this is a valid 
way to pass the thread id.

The following Change in Sourcecode fixed the problem for me:

MessageList.java
public final void onCreate
...
        if (this.uri != null) {
            if (!this.uri.toString().startsWith(URI)) {
                this.uri = Uri.parse(URI + this.uri.getLastPathSegment());
            }
            this.parseIntent(i);
        } else {
            if (i.getExtras().containsKey("thread_id")) {
                this.uri = Uri.parse(URI
                        + Long.toString(i.getExtras().getLong("thread_id")));
                this.parseIntent(i);
            }
        }


Viele Grüße,
Joscha Arenz
```

Original comment by `jos...@schallwellenreiter.org` on 2 Sep 2010 at 2:30

**Comment by GoogleCodeExporter** [comment]
```
Sorry, wrong (buggy) Code-Segment, the previous one crashes on normal SMS 
Intents without Extras ;)

Correct & working:

        this.uri = i.getData();
        if (this.uri != null) {
            if (!this.uri.toString().startsWith(URI)) {
                this.uri = Uri.parse(URI + this.uri.getLastPathSegment());
            }
            this.parseIntent(i);
        } else {
            if (i.hasExtra("thread_id")) {
                this.uri = Uri.parse(URI
                        + Long.toString(i.getExtras().getLong("thread_id")));
                this.parseIntent(i);
            }
        }
```

Original comment by `jos...@schallwellenreiter.org` on 2 Sep 2010 at 2:38

**Comment by GoogleCodeExporter** [comment]
```
please try this fix.
```

Original comment by `felix.bechstein` on 11 Sep 2010 at 1:01
- Changed state: **ShouldBeFixed**

Attachments:
- [SMSdroid-release.apk](https://storage.googleapis.com/google-code-attachments/websmsdroid/issue-318/comment-8/SMSdroid-release.apk)

**Comment by GoogleCodeExporter** [comment]
```
i i still get a null pointer exception when i try to open a sms.
```

Original comment by `jos...@schallwellenreiter.org` on 12 Sep 2010 at 12:54

**Comment by GoogleCodeExporter** [comment]
```
in parseIntent() i guess?
```

Original comment by `felix.bechstein` on 12 Sep 2010 at 8:33
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
D/SMSdroid( 6408): ml: onCreate()
D/SMSdroid( 6408): ml: got intent: android.intent.action.VIEW
D/SMSdroid( 6408): ml: got uri: null
W/Bundle  ( 6408): Key thread_id expected String but value was a 
java.lang.Long.  The default value <null> was returned.
W/Bundle  ( 6408): Attempt to cast generated internal exception:
W/Bundle  ( 6408): java.lang.ClassCastException: java.lang.Long
W/Bundle  ( 6408): at android.os.Bundle.getString(Bundle.java:977)
W/Bundle  ( 6408): at android.content.Intent.getStringExtra(Intent.java:3250)
W/Bundle  ( 6408): at 
de.ub0r.android.smsdroid.MessageList.parseIntent(MessageList.java:163)
W/Bundle  ( 6408): at 
de.ub0r.android.smsdroid.MessageList.onCreate(MessageList.java:114)
W/Bundle  ( 6408): at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
W/Bundle  ( 6408): at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
W/Bundle  ( 6408): at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
W/Bundle  ( 6408): at 
android.app.ActivityThread.access$2200(ActivityThread.java:119)
W/Bundle  ( 6408): at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
W/Bundle  ( 6408): at android.os.Handler.dispatchMessage(Handler.java:99)
W/Bundle  ( 6408): at android.os.Looper.loop(Looper.java:123)
W/Bundle  ( 6408): at android.app.ActivityThread.main(ActivityThread.java:4363)
W/Bundle  ( 6408): at java.lang.reflect.Method.invokeNative(Native Method)
W/Bundle  ( 6408): at java.lang.reflect.Method.invoke(Method.java:521)
W/Bundle  ( 6408): at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
W/Bundle  ( 6408): at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
W/Bundle  ( 6408): at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime( 6408): Shutting down VM

without trying: I guess using getLongExtras() instead of getStringExtras should 
do the trick.
```

Original comment by `jos...@schallwellenreiter.org` on 12 Sep 2010 at 8:39

**Comment by GoogleCodeExporter** [comment]
```
kk. i thought it gets casted automatically like in Cursor.

please try this one
```

Original comment by `felix.bechstein` on 12 Sep 2010 at 9:50

Attachments:
- [SMSdroid-release.apk](https://storage.googleapis.com/google-code-attachments/websmsdroid/issue-318/comment-12/SMSdroid-release.apk)

**Comment by GoogleCodeExporter** [comment]
```
Hi,
this Version seems to work without Problems.

Thanks!
```

Original comment by `jos...@schallwellenreiter.org` on 12 Sep 2010 at 11:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `felix.bechstein` on 13 Sep 2010 at 5:06
- Changed state: **ShouldBeFixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `felix.bechstein` on 14 Sep 2010 at 4:26
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
still having this issue
```

Original comment by `ktol...@gmail.com` on 14 Sep 2010 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
still getting FC when using the LauncherPro messaging widget.
```

Original comment by `Mike.Ter...@gmail.com` on 14 Sep 2010 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
then install the apk from comment #12 and send me your logs.
```

Original comment by `felix.bechstein` on 15 Sep 2010 at 4:35
- Changed state: **NeedMoreInfos**

**Comment by GoogleCodeExporter** [comment]
```
I just installed the apk from #12 and this works just fine.
The Version from the Market didn't.
```

Original comment by `Mike.Ter...@gmail.com` on 15 Sep 2010 at 10:37

**Comment by GoogleCodeExporter** [comment]
```
my bad, i fixed it on an other pc as i build the apk for the market. and i 
forgot to check in the changes before moving to the notebook :(

please confirm, that the attached apk is fixing the issue.
```

Original comment by `felix.bechstein` on 15 Sep 2010 at 4:54
- Changed state: **ShouldBeFixed**

Attachments:
- [SMSdroid-release.apk](https://storage.googleapis.com/google-code-attachments/websmsdroid/issue-318/comment-20/SMSdroid-release.apk)

**Comment by GoogleCodeExporter** [comment]
```
yes, the attached apk works. 
```

Original comment by `ktol...@gmail.com` on 15 Sep 2010 at 5:30

**Comment by GoogleCodeExporter** [comment]
```
I confirm.
```

Original comment by `bratf...@googlemail.com` on 15 Sep 2010 at 5:31

**Comment by GoogleCodeExporter** [comment]
```
Unfortunately one cannot define individual standard applications in the widget 
for viewing and writing messages. When I push the "new message" button in the 
widget, I get a "Fehler beim Laden des Threads". I guess it could be 
implemented that smsdroid automatically launches websms when it gets the 
request without a valid/certain thread argument.
```

Original comment by `bratf...@googlemail.com` on 15 Sep 2010 at 5:56

**Comment by GoogleCodeExporter** [comment]
```
seems to be very crude software :(
why the hell are there standard intents provided by android, when this app 
ignores it all..

i would prefer to launch the standard "new sms" intent when no thread_id is 
given.
i'll implement it as soon there is some time. be patient and read to test it.
```

Original comment by `felix.bechstein` on 15 Sep 2010 at 9:26
- Changed state: **Accepted**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Ok, thank you for taking the time to correct other's shortcomings ;)
I'll test it when ready.

I also posted the issue on the Dev's forum, let's see what'll happen.
```

Original comment by `bratf...@googlemail.com` on 16 Sep 2010 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
please try this one
```

Original comment by `felix.bechstein` on 16 Sep 2010 at 4:38
- Changed state: **Started**

Attachments:
- [SMSdroid-release.apk](https://storage.googleapis.com/google-code-attachments/websmsdroid/issue-318/comment-26/SMSdroid-release.apk)

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Almost does it. Websms starts up, but the error message is still displayed.
```

Original comment by `bratf...@googlemail.com` on 16 Sep 2010 at 6:29

**Comment by GoogleCodeExporter** [comment]
```
Though I don't know if it is supposed to do that. Maybe you left it in on 
purpose?!
```

Original comment by `bratf...@googlemail.com` on 16 Sep 2010 at 6:32

**Comment by GoogleCodeExporter** [comment]
```
just tell me the error message.
and send me your device's log after reproducing the error.
```

Original comment by `felix.bechstein` on 16 Sep 2010 at 6:56

**Comment by GoogleCodeExporter** [comment]
```
Fehler beim Laden des Threads!
```

Original comment by `bratf...@googlemail.com` on 16 Sep 2010 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
this should work now.
```

Original comment by `felix.bechstein` on 16 Sep 2010 at 7:14
- Changed state: **ShouldBeFixed**

Attachments:
- [SMSdroid-release.apk](https://storage.googleapis.com/google-code-attachments/websmsdroid/issue-318/comment-32/SMSdroid-release.apk)

**Comment by GoogleCodeExporter** [comment]
```
Yes, works flawlessly now. Vielen Dank ;)
```

Original comment by `bratf...@googlemail.com` on 16 Sep 2010 at 7:27

**Comment by GoogleCodeExporter** [comment]
Original comment by `felix.bechstein` on 17 Sep 2010 at 4:54
- Changed state: **Fixed**
