### ISSUE TITLE
SMSdroid looses all sms

### ISSUE THREAD

**Issue by GoogleCodeExporter** [satyajit319/websmsdroid#356]
```
What steps will reproduce the problem?
1. ?
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
SMSdroid 0.2.3.2, Samsung Galaxy S, Android 2.1

Please provide any additional information below.
smsdroid looses all sms... completely!
sms are completely gone then, other tools also don't show them anymore.
Couldn't distinguish a reason. Happened 2 times now. Used SMSdroid since one 
month now. The first time i just started it and all sms were gone. The second 
time app didn't start, i had to reset phone and then i started smsDroid and all 
sms were gone...
```

Original issue reported on code.google.com by `gregor.g...@googlemail.com` on 11 Oct 2010 at 1:10

**Comment by GoogleCodeExporter** [comment]
```
just to be sure: even the standard sms app does not show the messages?

did you try to reset the cache in smsdroid?
```

Original comment by `felix.bechstein` on 12 Oct 2010 at 5:36
- Changed state: **NeedMoreInfos**
- Added labels: **Component-Logic**, **Priority-Critical**, **Product-SMSdroid**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Since today I have the same issue. (Cache alreday cleared, Smsdroid 0.2.3.2, 
HTC Legened current stockrom)
This morning I've received a sms and answered via WebSMS using the "Answer" - 
Button from sms thread. (After sending the message, I just put the phone on the 
desk without doing any additional action like press "Back" or "Home" - Key).
Right now I started to write a new sms, so I "reactivate" the phone from 
standby (by unlocking lockscreen) and wondered why I see a "Blank" sms-droind. 
Only the Button "New Message" appeared and the rest of the screen was blank. 
After writing a new smsm this one is the only one which is shown by smsdroid 
and stock app!
I' ve cleared the cache and restarted my phone - nothing happened...
Please don't tell me that all my messages (1000+) are gone...
```

Original comment by `a.jeu...@gmail.com` on 23 Oct 2010 at 10:15

**Comment by GoogleCodeExporter** [comment]
```
i guess they are :/

but i really do not know why.
i checked all references to ContentResolver.delete() in smsdroid, websms and 
websms-api.

websms and it's api do not have a reference.
smsdroid's only reference is in the confirmation dialog for deleting messages.
you never touched this in between, right?
```

Original comment by `felix.bechstein` on 23 Oct 2010 at 11:22

**Comment by GoogleCodeExporter** [comment]
```
Is's a pity :(
No, I did not touch anything after pushing "send" from menu in websms. 
(Normally websms sends the messages and closes itself, so the choosen smsthread 
(not the sms-overview) from smsdroid returns to the top of activity thread...)
I just noticed how the websms activity "slides" away and then I put my mobile 
to the desk. 
A few hours later I only pushed the "power-button" to let the mobile wake up. 
After that I "draw" the "Entsperrungsmuster" from Lockscreen.
At this moment I saw the empty overview screen from smsdroid, only "New 
Message" at the top.
So, the only touch to the display was to unlock the phone...
(Now I will see if MyBackup really works...)

```

Original comment by `a.jeu...@gmail.com` on 23 Oct 2010 at 1:18

**Comment by GoogleCodeExporter** [comment]
```
Same here. The app crashed with a message ending ......android.mms and all sms 
were gone. I didn' try to send a mms, only sent a sms and then got the error.
That happend the second time.

```

Original comment by `lzin...@gmail.com` on 26 Oct 2010 at 1:04

**Comment by GoogleCodeExporter** [comment]
```
Take a look at my logs:
http://pastebin.ca/1973641

I cutted out the interesting part
```

Original comment by `lzin...@gmail.com` on 26 Oct 2010 at 1:21

**Comment by GoogleCodeExporter** [comment]
```
well. this is quite shocking!
some app (i'm still not sure it's mine) is making the inner database of the 
standard sms app (android.mms) break:

Caused by: android.database.sqlite.SQLiteDatabaseCorruptException: database 
disk image is malformed

i think, at this time android.mms is flashing the database. :(

@lizins77: do you have the full log? there is some trace above the snipped, it 
might be interessting too.
```

Original comment by `felix.bechstein` on 26 Oct 2010 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
Find the full log here:

http://pastebin.ca/1974664


```

Original comment by `lzin...@gmail.com` on 27 Oct 2010 at 1:27

**Comment by GoogleCodeExporter** [comment]
```
dis anyone of you set a custom language in any of the app's preferences?
i really have no clue, why the android_metadata table is missing in mms's 
database.
none of my apps is able to touch it..
```

Original comment by `felix.bechstein` on 2 Nov 2010 at 5:04

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I don't understand what you're meaning... My "custom" language is 
german, if any application let me set this, I'll do so. (Did you mean that?)
```

Original comment by `a.jeu...@gmail.com` on 2 Nov 2010 at 10:37

**Comment by GoogleCodeExporter** [comment]
```
with latest versions of my apps you can select the language in the app too.
i added this feature for eg. hungarian users, which mostly are not able to set 
their language in android system.
that's what i meant with custom language.
most will use the default.

i asked because the only trace like this is produced from androids setLocale().
```

Original comment by `felix.bechstein` on 2 Nov 2010 at 11:01

**Comment by GoogleCodeExporter** [comment]
```
I didn't change anything in the language settings. So I think I use the default 
one.
```

Original comment by `lzin...@gmail.com` on 3 Nov 2010 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
please update both, websms and smsdroid.
i hope this was some kind of inconsistant state within the build.

please report, if this happens again.

and: is some kind of custom home screen or anything running on your phone?
```

Original comment by `felix.bechstein` on 7 Nov 2010 at 1:48

**Comment by GoogleCodeExporter** [comment]
```
Ok, i've updated both. I do not use any custom home screen, launchers or 
whatever. My HTC Legend is still running stock ROM with Sense.
```

Original comment by `a.jeu...@gmail.com` on 7 Nov 2010 at 2:48

**Comment by GoogleCodeExporter** [comment]
```
i had this problem too - twice (BEFORE TODAY'S UPDATE). sms was received, and 
sms-droid widget was showing 1 unread sms. i clicked them - SMSdroid was 
crashed. After rebooting phone and reseting SMSdroid's cache - standard app was 
seen old sms, but smsdroid only new (post-crash).
The newest update (0.2.4) is testing...
```

Original comment by `ximonline@gmail.com` on 7 Nov 2010 at 6:02

**Comment by GoogleCodeExporter** [comment]
```
as long the standard app shows sms, this is not this issue.
but please send me logs if something like this happens.
as i'm unable to reproduce this problem here, i need more input to fix it.
thx for your coorporation.
```

Original comment by `felix.bechstein` on 7 Nov 2010 at 6:12

**Comment by GoogleCodeExporter** [comment]
```
I updated too. Until now no problems. Let's wait some time.
```

Original comment by `lzin...@gmail.com` on 14 Nov 2010 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
Strange... today all my messages were lost again. This time there some crashed 
from sms-droid and from missedreminder. Both app crash alternating over and 
over again, so i've restarted the phone. After restart all sms were gone...
```

Original comment by `a.jeu...@gmail.com` on 1 Dec 2010 at 5:44

**Comment by GoogleCodeExporter** [comment]
```
Today I lost all my messages, too.
While I was trying to solve another problem with SMSdroid (no notification for 
incoming SMS all my SMS were lost.
Luckily I made a complete backup two days ago...

```

Original comment by `florian....@gmail.com` on 11 Dec 2010 at 2:07

**Comment by GoogleCodeExporter** [comment]
```
this issue should be fixed with current development release.

please test+verify.

http://code.google.com/p/websmsdroid/downloads/detail?name=SMSdroid-0.2.4-dev-20
101230.apk
```

Original comment by `felix.bechstein` on 30 Dec 2010 at 1:25
- Changed state: **ShouldBeFixed**

**Comment by GoogleCodeExporter** [comment]
```
i assume this bug as fixed.
i still have this issue starred. please comment it, if this is still a problem 
with the new market release.
```

Original comment by `felix.bechstein` on 4 Jan 2011 at 8:56
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi, last night i've lost nearly all sms again. All but one single thread 
including one sms, all others are gone. (The same is in stock app)
And there is a new thread with a new sms from last night. And now something 
strange:
The time of the new says 1:54, but i received the signal that a new message was 
received this morning at about 9:30. This happend when I took my legend from 
the desk and tried to unlock the phone. At this moment the notification was 
shown and the led began to flash. 
I've opened the new message and after reading a noticed that all others but one 
and the new one are lost!
I'm really pi**ed off and wondering how google implemented a simple database 
for sms which is so unstable...
```

Original comment by `realgun4...@gmail.com` on 19 Mar 2011 at 9:45

**Comment by GoogleCodeExporter** [comment]
```
i guess this happend like this:

in the same moment as the sms arrived, the sms db was dropped.
a few moments later the new message was put into it, but smsdroid stopped 
looking for it.
when unlocking the phone the widget (?) reloads and searches for new messages 
again.

i'll try to build a version with other handling for new messages. please stay 
tuned/patient, as i'm quite busy theses days with my main job. :/
```

Original comment by `f...@ub0r.de` on 21 Mar 2011 at 7:42
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
well. anything i could do was adding an other delay of 500ms to prevent the 
phone from reading parallel to androids write.
please test the attached build.

but never the less, i can hardly imagine that reading the db makes android 
dropping it. :x
```

Original comment by `f...@ub0r.de` on 22 Mar 2011 at 8:40
- Changed state: **ShouldBeFixed**

Attachments:
- [SMSdroid-release.apk](https://storage.googleapis.com/google-code-attachments/websmsdroid/issue-356/comment-24/SMSdroid-release.apk)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for quick release a new build. I've installed and testing now, seems to 
be working fine! I don't think that this a bug of smsdroid, i've found some 
more postings about this issue. Seems to be a problem within adroids database 
handling itself when the internal memory becomes low, but google wether confirm 
nor deny...
```

Original comment by `a.jeu...@gmail.com` on 22 Mar 2011 at 9:42

**Comment by GoogleCodeExporter** [comment]
```
hm :/

and do not run task killer on any app that uses databses ;)
this may currupt the it like this one:

i digged a bit in stack traces i got in android market from some users like

android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is 
malformed
at android.database.sqlite.SQLiteQuery.native_fill_window(Native Method)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:70)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:299)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:280)
at android.content.ContentResolver.query(ContentResolver.java:251)
at 
de.ub0r.android.callmeter.data.LogRunnerService.getMaxDate(LogRunnerService.java
:195)
```

Original comment by `f...@ub0r.de` on 22 Mar 2011 at 10:23

**Comment by GoogleCodeExporter** [comment]
```
Year, using a task killer can cause some unwanted sideeffects... for myself, 
i'm a software developer and so I do not use task killers (or something like 
this) without exactly knowing the consequences ;)
```

Original comment by `a.jeu...@gmail.com` on 23 Mar 2011 at 11:14

**Comment by GoogleCodeExporter** [comment]
```
Ok, I've got some crashes with the new version. Each time when I leave smsdroid 
with "home-key", the next start of smsdroid will crash ("Die Anwendung SMSdroid 
wurde... & Schließen erzwingen").
The next start after this works fine. Also leaving the app by pressing 
"back-key" works as expected.
```

Original comment by `a.jeu...@gmail.com` on 24 Mar 2011 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
well, sending device logs may help to fix that problem ;)
```

Original comment by `f...@ub0r.de` on 24 Mar 2011 at 6:46
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Ups, sorry - I forgot about that feature... logs are sent now.
```

Original comment by `a.jeu...@gmail.com` on 24 Mar 2011 at 10:19

**Comment by GoogleCodeExporter** [comment]
```
please test this build
```

Original comment by `f...@ub0r.de` on 25 Mar 2011 at 5:19
- Changed state: **ShouldBeFixed**

Attachments:
- [SMSdroid-release.apk](https://storage.googleapis.com/google-code-attachments/websmsdroid/issue-356/comment-31/SMSdroid-release.apk)

**Comment by GoogleCodeExporter** [comment]
```
Thanks, crash seems to be fixed.
```

Original comment by `a.jeu...@gmail.com` on 25 Mar 2011 at 7:01

**Comment by GoogleCodeExporter** [comment]
```
any crashes since march?
```

Original comment by `f...@ub0r.de` on 7 May 2011 at 5:48

**Comment by GoogleCodeExporter** [comment]
```
No crashes (which are killing my sms) since march. But sometimes smsdroid 
reacts very slow and I get the "wait/force close" dialog. I've chosen always 
"wait" and a few minutes later smsdroid works at all.
```

Original comment by `a.jeu...@gmail.com` on 7 May 2011 at 10:25

**Comment by GoogleCodeExporter** [comment]
```
ok. i'll close this issue.
feel free to add a comment if something bad happens again.
```

Original comment by `f...@ub0r.de` on 8 May 2011 at 9:09
- Changed state: **Fixed**
